stages:
  - build

build:
  stage: build
  image: archlinux:latest
  before_script:
    - pacman -Sy --noconfirm
    - pacman -S --noconfirm archiso python base-devel sudo
    - useradd -m builduser
    - 'echo "builduser ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/builduser'
    - chown -R builduser:builduser $CI_PROJECT_DIR
  script:
    - su - builduser -c "cd $CI_PROJECT_DIR && python ./scripts/python/main.py prepare"
    - su - builduser -c "cd $CI_PROJECT_DIR && python ./scripts/python/main.py build"
    - curl --progress-bar --upload-file ./out/*.iso https://transfer.sh/BakeryOS_Final.iso > f.txt
    - cat f.txt
