[options]
HoldPkg = pacman glibc
Architecture = auto
ParallelDownloads = 5
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional

[bakery-os]
SigLevel = Never
Server = https://repo.bakeryos.smtdfc.space/$arch

[custom]
SigLevel = Optional TrustAll
Server = file:///home/smtdfc/Projects/BakeryOS-Project/bakeryos/data/local-repo

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

