[options]
HoldPkg     = pacman glibc
Architecture = auto
CheckSpace
Color
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[bakeryos]
Include = /etc/pacman.d/bakeryos_mirrorlist
