---
# Cấu hình cho initramfs
# Calamares sẽ gọi lệnh này sau khi cài đặt xong hệ thống
kernel: "/boot/vmlinuz-linux"
initramfs: "/boot/initramfs-linux.img"
# Đảm bảo đường dẫn này đúng với cách bạn cài đặt kernel