
branding: default
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: false
quit-at-end: false

modules-search: [local]

instances:
- module:       partition
  name:         partition

- module:       users
  name:         users

sequence:
- show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - summary

- exec:
    - partition
    - mount
    - unpackfs
    - machineid
    - fstab
    - locale
    - keyboard
    - localecfg
    - users
    - displaymanager
    - grubcfg
    - bootloader
    - umount
- show:
    - finished
